services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - 'mysql_data:/mysql/data'

  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mysqldb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=$DATABASE_PORT
    links:
      - mysqldb
    volumes:
      - "./src:/application/src"


volumes:
   mysql_data:
     driver: local
